export const solid_blocks = [
	"acacia_log",
	"amethyst_block",
	"ancient_debris",
	"bamboo_block",
	"bamboo_double_slab",
	"bamboo_mosaic",
	"bamboo_mosaic_double_slab",
	"bamboo_planks",
	"barrel",
	"basalt",
	"bee_nest",
	"beehive",
	"birch_log",
	"black_concrete",
	"black_concrete_powder",
	"black_glazed_terracotta",
	"black_terracotta",
	"black_wool",
	"blackstone",
	"blackstone_double_slab",
	"blast_furnace",
	"blue_concrete",
	"blue_concrete_powder",
	"blue_glazed_terracotta",
	"blue_ice",
	"blue_terracotta",
	"blue_wool",
	"bone_block",
	"bookshelf",
	"brick_block",
	"brown_concrete",
	"brown_concrete_powder",
	"brown_glazed_terracotta",
	"brown_mushroom_block",
	"brown_terracotta",
	"brown_wool",
	"budding_amethyst",
	"calcite",
	"cartography_table",
	"carved_pumpkin",
	"cherry_double_slab",
	"cherry_log",
	"cherry_planks",
	"cherry_wood",
	"chiseled_bookshelf",
	"chiseled_deepslate",
	"chiseled_nether_bricks",
	"chiseled_polished_blackstone",
	"clay",
	"coal_block",
	"coal_ore",
	"cobbled_deepslate",
	"cobbled_deepslate_double_slab",
	"cobblestone",
	"copper_block",
	"copper_ore",
	"coral_block",
	"cracked_deepslate_bricks",
	"cracked_deepslate_tiles",
	"cracked_nether_bricks",
	"cracked_polished_blackstone_bricks",
	"crafting_table",
	"crimson_double_slab",
	"crimson_hyphae",
	"crimson_nylium",
	"crimson_planks",
	"crimson_stem",
	"cut_copper",
	"cyan_concrete",
	"cyan_concrete_powder",
	"cyan_glazed_terracotta",
	"cyan_terracotta",
	"cyan_wool",
	"dark_oak_log",
	"deepslate",
	"deepslate_brick_double_slab",
	"deepslate_bricks",
	"deepslate_coal_ore",
	"deepslate_copper_ore",
	"deepslate_diamond_ore",
	"deepslate_emerald_ore",
	"deepslate_gold_ore",
	"deepslate_iron_ore",
	"deepslate_lapis_ore",
	"deepslate_redstone_ore",
	"deepslate_tile_double_slab",
	"deepslate_tiles",
	"diamond_block",
	"diamond_ore",
	"dirt",
	"dirt_with_roots",
	"dispenser",
	"dried_kelp_block",
	"dripstone_block",
	"dropper",
	"emerald_block",
	"emerald_ore",
	"end_bricks",
	"end_stone",
	"exposed_copper",
	"exposed_cut_copper",
	"exposed_double_cut_copper_slab",
	"fletching_table",
	"furnace",
	"gilded_blackstone",
	"gold_block",
	"gold_ore",
	"grass_block",
	"gravel",
	"gray_concrete",
	"gray_concrete_powder",
	"gray_glazed_terracotta",
	"gray_terracotta",
	"gray_wool",
	"green_concrete",
	"green_concrete_powder",
	"green_glazed_terracotta",
	"green_terracotta",
	"green_wool",
	"hardened_clay",
	"hay_block",
	"honeycomb_block",
	"infested_deepslate",
	"iron_block",
	"iron_ore",
	"jukebox",
	"jungle_log",
	"lapis_block",
	"lapis_ore",
	"light_blue_concrete",
	"light_blue_concrete_powder",
	"light_blue_glazed_terracotta",
	"light_blue_terracotta",
	"light_blue_wool",
	"light_gray_concrete",
	"light_gray_concrete_powder",
	"light_gray_terracotta",
	"light_gray_wool",
	"lime_concrete",
	"lime_concrete_powder",
	"lime_glazed_terracotta",
	"lime_terracotta",
	"lime_wool",
	"lodestone",
	"loom",
	"magenta_concrete",
	"magenta_concrete_powder",
	"magenta_glazed_terracotta",
	"magenta_terracotta",
	"magenta_wool",
	"mangrove_double_slab",
	"mangrove_log",
	"mangrove_planks",
	"mangrove_wood",
	"melon_block",
	"mob_spawner",
	"monster_egg",
	"moss_block",
	"mossy_cobblestone",
	"mud",
	"mud_brick_double_slab",
	"mud_bricks",
	"muddy_mangrove_roots",
	"mycelium",
	"nether_brick",
	"nether_gold_ore",
	"nether_wart_block",
	"netherite_block",
	"netherrack",
	"noteblock",
	"oak_log",
	"obsidian",
	"orange_concrete",
	"orange_concrete_powder",
	"orange_glazed_terracotta",
	"orange_terracotta",
	"orange_wool",
	"oxidized_copper",
	"oxidized_cut_copper",
	"oxidized_double_cut_copper_slab",
	"packed_ice",
	"packed_mud",
	"pink_concrete",
	"pink_concrete_powder",
	"pink_glazed_terracotta",
	"pink_terracotta",
	"pink_wool",
	"podzol",
	"polished_basalt",
	"polished_blackstone",
	"polished_blackstone_brick_double_slab",
	"polished_blackstone_bricks",
	"polished_blackstone_double_slab",
	"polished_deepslate",
	"polished_deepslate_double_slab",
	"prismarine",
	"pumpkin",
	"purple_concrete",
	"purple_concrete_powder",
	"purple_glazed_terracotta",
	"purple_terracotta",
	"purple_wool",
	"purpur_block",
	"quartz_block",
	"quartz_bricks",
	"quartz_ore",
	"raw_copper_block",
	"raw_gold_block",
	"raw_iron_block",
	"red_concrete",
	"red_concrete_powder",
	"red_glazed_terracotta",
	"red_mushroom_block",
	"red_nether_brick",
	"red_sandstone",
	"red_terracotta",
	"red_wool",
	"redstone_lamp",
	"redstone_ore",
	"reinforced_deepslate",
	"sand",
	"sandstone",
	"sculk",
	"sculk_catalyst",
	"silver_glazed_terracotta",
	"slime",
	"smithing_table",
	"smoker",
	"smooth_basalt",
	"smooth_stone",
	"snow",
	"soul_sand",
	"soul_soil",
	"sponge",
	"spruce_log",
	"stone",
	"stonebrick",
	"stripped_acacia_log",
	"stripped_bamboo_block",
	"stripped_birch_log",
	"stripped_cherry_log",
	"stripped_cherry_wood",
	"stripped_crimson_hyphae",
	"stripped_crimson_stem",
	"stripped_dark_oak_log",
	"stripped_jungle_log",
	"stripped_mangrove_log",
	"stripped_mangrove_wood",
	"stripped_oak_log",
	"stripped_spruce_log",
	"stripped_warped_hyphae",
	"stripped_warped_stem",
	"suspicious_gravel",
	"suspicious_sand",
	"target",
	"tnt",
	"tuff",
	"warped_double_slab",
	"warped_hyphae",
	"warped_nylium",
	"warped_planks",
	"warped_stem",
	"warped_wart_block",
	"waxed_copper",
	"waxed_cut_copper",
	"waxed_double_cut_copper_slab",
	"waxed_exposed_copper",
	"waxed_exposed_cut_copper",
	"waxed_exposed_double_cut_copper_slab",
	"waxed_oxidized_copper",
	"waxed_oxidized_cut_copper",
	"waxed_weathered_copper",
	"waxed_weathered_cut_copper",
	"waxed_weathered_double_cut_copper_slab",
	"weathered_copper",
	"weathered_cut_copper",
	"weathered_double_cut_copper_slab",
	"white_concrete",
	"white_concrete_powder",
	"white_glazed_terracotta",
	"white_terracotta",
	"white_wool",
	"wood",
	"yellow_concrete",
	"yellow_concrete_powder",
	"yellow_glazed_terracotta",
	"yellow_terracotta",
	"yellow_wool",
	"oak_planks",
	"spruce_planks",
	"birch_planks",
	"jungle_planks",
	"acacia_planks",
	"dark_oak_planks",
	"granite",
	"polished_granite",
	"diorite",
	"polished_diorite",
	"andesite",
	"polished_andesite",
	"yasser444:copper_ore",
	"yasser444:lapis_lazuli_ore",
	"yasser444:redstone_ore",
	"yasser444:deepslate_copper_ore",
	"yasser444:deepslate_lapis_lazuli_ore",
	"yasser444:deepslate_redstone_ore",
	"yasser444:nether_gold_ore"
]
export const non_solids = [
	"air",
	"standing_banner",
	"wall_banner",
	"cave_vines",
	"tube_coral",
	"brain_coral",
	"bubble_coral",
	"fire_coral",
	"horn_coral",
	"dead_tube_coral",
	"dead_brain_coral",
	"dead_bubble_coral",
	"dead_fire_coral",
	"dead_horn_coral",
	"coral_fan",
	"coral_fan_dead",
	"coral_fan_hang",
	"coral_fan_hang2",
	"coral_fan_hang3",
	"deadbush",
	"tallgrass",
	"yellow_flower",
	"red_flower",
	"double_plant",
	"torchflower",
	"pitcher_plant",
	"crimson_fungus",
	"warped_fungus",
	"nether_sprouts",
	"hanging_roots",
	"brown_mushroom",
	"red_mushroom",
	"nether_wart",
	"pink_petals",
	"rail",
	"activator_rail",
	"detector_rail",
	"golden_rail",
	"crimson_roots",
	"warped_roots",
	"sapling",
	"cherry_sapling",
	"scaffolding",
	"sculk_vein",
	"standing_sign",
	"spruce_standing_sign",
	"birch_standing_sign",
	"jungle_standing_sign",
	"acacia_standing_sign",
	"darkoak_standing_sign",
	"mangrove_standing_sign",
	"cherry_standing_sign",
	"bamboo_standing_sign",
	"crimson_standing_sign",
	"warped_standing_sign",
	"wall_sign",
	"spruce_wall_sign",
	"birch_wall_sign",
	"jungle_wall_sign",
	"acacia_wall_sign",
	"darkoak_wall_sign",
	"mangrove_wall_sign",
	"cherry_wall_sign",
	"bamboo_wall_sign",
	"crimson_wall_sign",
	"warped_wall_sign",
	"small_dripleaf_block",
	"reeds",
	"tripwire_hook",
	"trip_wire",
	"twisting_vines",
	"vine",
	"weeping_vines"
]
export const insta_push = [
	"tinted_glass",
	"glass",
	"glass_pane",
	"white_stained_glass",
	"light_gray_stained_glass",
	"gray_stained_glass",
	"black_stained_glass",
	"brown_stained_glass",
	"red_stained_glass",
	"orange_stained_glass",
	"yellow_stained_glass",
	"lime_stained_glass",
	"green_stained_glass",
	"light_blue_stained_glass",
	"cyan_stained_glass",
	"blue_stained_glass",
	"purple_stained_glass",
	"magenta_stained_glass",
	"pink_stained_glass",
	"white_stained_glass_pane",
	"light_gray_stained_glass_pane",
	"gray_stained_glass_pane",
	"black_stained_glass_pane",
	"brown_stained_glass_pane",
	"red_stained_glass_pane",
	"orange_stained_glass_pane",
	"yellow_stained_glass_pane",
	"lime_stained_glass_pane",
	"green_stained_glass_pane",
	"light_blue_stained_glass_pane",
	"cyan_stained_glass_pane",
	"blue_stained_glass_pane",
	"purple_stained_glass_pane",
	"magenta_stained_glass_pane",
	"pink_stained_glass_pane"
]
export const biome_names = {
	plains: "§aPlains",
	sunflower_plains: "§aSunflower Plains",
	taiga: "§2Taiga",
	taiga_hills: "§2Taiga Hills",
	taiga_mountains: "§2Taiga Mountains",
	snowy_taiga: "§3Snowy Taiga",
	snowy_taiga_hills: "§sSnowy Taiga Hills",
	snowy_taiga_mountains: "§sSnowy Taiga Mountains",
	old_growth_pine_taiga: "§2Old Growth Pine Taiga",
	mega_taiga: "§4Mega Taiga",
	old_growth_spruce_taiga: "§2Old Growth Spruce Taiga",
	redwood_taiga: "§mRedwood Taiga",
	swamp: "§qSwamp",
	swamp_hills: "§qSwamp Hills",
	mangrove_swamp: "§mMangrove Swamp",
	desert: "§6Desert",
	desert_hills: "§6Desert Hills",
	desert_lakes: "§gDesert Lakes",
	jungle: "§qJungle",
	jungle_hills: "§qJungle Hills",
	modified_jungle: "§qModified Jungle",
	sparse_jungle: "§2Sparse Jungle",
	jungle_edge: "§qJungle Edge",
	bamboo_jungle: "§2Bamboo Jungle",
	bamboo_jungle_hills: "§2Bamboo Jungle Hills",
	birch_forest: "§aBirch Forest",
	birch_forest_hills: "§aBirch Forest Hills",
	old_growth_birch_forest: "§aOld Growth Birch Forest",
	tall_birch_hills: "§aTall Birch Hills",
	dark_forest: "§qDark Forest",
	roofed_forest: "§qRoofed Forest",
	savanna: "§pSavanna",
	savanna_plateau: "§pSavanna Plateau",
	windswept_savanna: "§pWindswept Savanna",
	shattered_savanna: "§pShattered Savanna",
	mushroom_fields: "§uMushroom Fields",
	mushroom_field_shore: "§uMushroom Field Shore",
	windswept_hills: "§7Windswept Hills",
	gravelly_mountains: "§7Gravelly Mountains",
	windswept_forest: "§jWindswept Forest",
	gravelly_forest: "§jGravelly Forest",
	mountain_edge: "§7Mountain Edge",
	ocean: "§9Ocean",
	warm_ocean: "§bWarm Ocean",
	lukewarm_ocean: "§sLukewarm Ocean",
	cold_ocean: "§3Cold Ocean",
	frozen_ocean: "§tFrozen Ocean",
	deep_ocean: "§1Deep Ocean",
	deep_warm_ocean: "§sDeep Warm Ocean",
	deep_lukewarm_ocean: "§tDeep Lukewarm Ocean",
	deep_cold_ocean: "§1Deep Cold Ocean",
	deep_frozen_ocean: "§tDeep Frozen Ocean",
	legacy_frozen_ocean: "§tLegacy Frozen Ocean",
	badlands: "§cBadlands",
	eroded_badlands: "§hEroded Badlands",
	badlands_plateau: "§nBadlands Plateau",
	wooded_badlands: "§jWooded Badlands",
	modified_badlands: "§cModified Badlands",
	modified_wooded_badlands: "§jModified Wooded Badlands",
	forest: "§2Forest",
	wooded_hills: "§2Wooded Hills",
	flower_forest: "§dFlower Forest",
	river: "§9River",
	frozen_river: "§bFrozen River",
	beach: "§eBeach",
	snowy_beach: "§fSnowy Beach",
	stony_shore: "§7Stony Shore",
	snowy_plains: "§fSnowy Plains",
	ice_spikes: "§bIce Spikes",
	meadow: "§qMeadow",
	grove: "§jGrove",
	cherry_grove: "§dCherry Grove",
	snowy_slopes: "§iSnowy Slopes",
	stony_peaks: "§8Stony Peaks",
	jagged_peaks: "§8Jagged Peaks",
	frozen_peaks: "§tFrozen Peaks",
	snowy_mountains: "§fSnowy Mountains",
	lush_caves: "§dLush Caves",
	dripstone_caves: "§nDripstone Caves",
	deep_dark: "§sDeep Dark",
	pale_garden: "§vPale Garden",
	nether_wastes: "§cNether Wastes",
	crimson_forest: "§mCrimson Forest",
	warped_forest: "§3Warped Forest",
	soulsand_valley: "§bSoul Sand Valley",
	basalt_deltas: "§8Basalt Deltas",
	the_end: "§5The End",
}
export const overworld_structures = [
    {
		id: 'igloo', x: -347.5, y: 71.06, z: -715.5,
		structure: 'Igloo', require: 'taiga',
		biome: biome_names.frozen_river,
		place: {x: -356, y: 69, z: -724},
	},
    {
		id: 'jungle_temple', x: -458.5, y: 70, z: 883.5,
		structure: 'Jungle Temple', require: 'jungle',
		biome: biome_names.jungle_edge,
		place: {x: -464, y: 65, z: 880},
	},
    {
        id: 'desert_pyramid', x: -761.5, y: 65, z: -270.5,
        structures: ['Desert Pyramid', 'Desert Well'], require: 'desert',
        biomes: [biome_names.desert_hills, biome_names.desert_lakes],
    },
    {
		id: 'ocean_monument', x: 632.5, y: 53, z: 759.5,
		structure: 'Ocean Monument', require: 'mushroom_island',
		biome: biome_names.lukewarm_ocean,
	},
    {
		id: 'swamp_hut', x: -252.5, y: 67, z: 516.5,  
		structure: 'Swamp Hut', require: 'swamp',
		biome: biome_names.swamp_hills,
		place: {x: -257 , y: 64, z: 511},
	},
    {
		id: 'mineshaft', x: 696.5, y: 33, z: -232.5,
		structure: 'Mineshaft', require: 'badlands',
		biome: biome_names.modified_badlands,
		place: {x: 684, y: 31, z: -248},
	},
    {
		id: 'pillager_outpost', x: -901.5, y: 94, z: 379.5,  
		structure: 'Pillager Outpost', require: 'savanna',
		biome: biome_names.savanna_plateau,
		place: {x: -910, y: 80, z: 370},
	},
    {
		id: 'woodland_mansion', x: 531.5, y: 64.06, z: -860.5,
		structure: 'Woodland Mansion', require: 'dark_forest',
		biome: biome_names.roofed_forest,
		place: {x: 521, y: 63, z: -871},
	},
    {
		id: 'ancient_city', x: 157.5, y: -37, z: 764.5,
		structure: 'Ancient City', require: 'deep_dark',
		biome: biome_names.deep_dark,
		place: [{x: 134, y: -51, z: 749}, {x: 112, y: -51, z: 757}, {x: 153, y: -51, z: 720}, {x: 180, y: -51, z: 752}, {x: 151, y: -51, z: 775}],
	},
    {
        id: 'ocean_ruins', x: -640.5, y: 46, z: 262.5, icon: 'shipwreck',
        structures: ['Warm Ocean Ruins', 'Cold Ocean Ruins', 'Shipwreck'], require: 'ocean',
        biomes: [biome_names.deep_warm_ocean, biome_names.deep_cold_ocean, biome_names.deep_lukewarm_ocean]
	},
    {
		id: 'trail_ruins', x: 130.5, y: 53, z: -830.5,
		structure: 'Trail Ruins', require: 'birch',
		biome: biome_names.old_growth_pine_taiga,
		place: {x: 120, y: 39, z: -859},
	},
    {
		id: 'trial_chambers', x: 375.5, y: 9, z: -491.5,
		structure: 'Trial Chambers', require: 'cherry',
		biome: biome_names.old_growth_spruce_taiga,
		place: {x: 361, y: 7, z: -519},
	},
]
export const nether_structures = [
    {
		id: 'nether_fortress', x: 75.5, y: 53, z: 142.5,
		structure: 'Nether Fortress',
		place: {x: 64, y: 52, z: 112},
	},
    { 
		id: 'bastion_remnants', x: -97.5, y: 65, z: 92.5,
		structure: 'Bastion Remnants',
		place: {x: -109, y: 64, z: 79},
	},
    {
		id: 'ruined_portal', x: -283.5, y: 18, z: 142.5,
		structure: 'Ruined Portal',
		place: {x: -291, y: 9, z: 133},
	},
]
export const destinations = {
	starter_island: { coords: {x: 0.5, y: 64, z: 0.5}, place: {x: -7, y: 60, z: -7}},
	desert_island: { coords: {x: 0.5, y: 64, z: 96.5}, place: {x: -7 , y: 60, z: 89}},
	jungle_island: { coords: {x: -94.5, y: 64, z: 0.5}, place: {x: -103 , y: 60, z: -7}},
	taiga_island: { coords: {x: 0.5, y: 64.12, z: -95.5}, place: {x: -7, y: 60, z: -103}},
	swamp_island: { coords: {x: 95.5, y: 64, z: 1.5}, place: {x: 89, y: 60, z: -7}},
	savanna_island: { coords: {x: 95.5, y: 64, z: 96.5}, place: {x: 89, y: 60, z: 89}},
	mushroom_island: { coords: {x: -94.5, y: 64, z: 95.5}, place: {x: -103, y: 60, z: 89}},
	birch_island: { coords: {x: -94.5, y: 64, z: -94.5}, place: {x: -103, y: 60, z: -103}},
	roofed_island: { coords: {x: 95.5, y: 64, z: -94.5}, place: {x: 89, y: 60, z: -103}},
	badlands_island: { coords: {x: 0.5, y: 64, z: 191.5}, place: {x: -7, y: 60, z: 185}},
	cherry_island: { coords: {x: -190.5, y: 64, z: 0.5}, place: {x: -199, y: 60, z: -7}},
	pale_island: { coords: {x: -0.5, y: 64, z: -190.5}, place: {x: -7, y: 60, z: -199}},
	ocean_island: { coords: {x: 192.5, y: 64, z: 0.5}},
	amethyst_island: { coords: {x: -43.5, y: 32, z: 144.5}, place: {x: -53, y: 26, z: 139}},
	lush_island: { coords: {x: -143.5, y: 32, z: -47.5}, place: {x: -153, y: 26, z: -57}},
	dripstone_island: { coords: {x: 44.5, y: 32, z: -143.5}, place: {x: 38, y: 26, z: -152}},
	deep_dark_island: { coords: {x: 144.5, y: -32, z: 48.5}, place: {x: 138 , y:-36, z: 42}},
	nether_portal: { coords: {x: 1.5, y: 64, z: 0.5}, dimension: "nether", place: {x: -7, y: 60, z: -7}},
	crimson_island: { coords: {x: 95.5, y: 64, z: 0.5}, dimension: "nether", place: {x: 89, y: 60, z: -7}},
	warped_island: { coords: {x: -94.5, y: 64, z: 0.5}, dimension: "nether", place: {x: -103, y: 60, z: -7}},
	basalt_island: { coords: {x: 0.5, y: 64, z: 94.5}, dimension: "nether", place: {x: -7, y: 60, z: 89}},
	soulsand_island: { coords: {x: 0.5, y: 64, z: -95.5}, dimension: "nether", place: {x: -7, y: 60, z: -103}},
	the_end: { coords: {x: 100.5, y: 50, z: 0.5}, dimension: "the_end"},
}
;[...overworld_structures, ...nether_structures].forEach(({id, x, y, z, place}) => destinations[id] = {coords: {x, y, z}, place})
nether_structures.forEach(({id}) => destinations[id].dimension = 'nether')

export const restorable_structures = {
    warm_ocean_ruins: {
        place: { x: -656, y: 40, z: 240 },
        visit: "ocean_ruins"
    },
    cold_ocean_ruins: {
        place: { x: -640, y: 40, z: 272 },
        visit: "ocean_ruins"
    },
    shipwreck: {
        place: { x: -656, y: 40, z: 256 },
        visit: "ocean_ruins"
    },
    desert_pyramid: {
        place: { x: -768, y: 62, z: -272 },
        visit: "desert_pyramid"
    },
    desert_well: {
        place: { x: -775, y: 62, z: -281 },
        visit: "desert_pyramid"
    },
}
Object.keys(destinations).forEach(id => {
	if (destinations[id].place) restorable_structures[id] = {
		place: destinations[id].place,
		visit: id
	}
})
