export const biome_names = {
	plains: "§aPlains",
	sunflower_plains: "§aSunflower Plains",
	taiga: "§2Taiga",
	taiga_hills: "§2Taiga Hills",
	taiga_mutated: "§2Taiga Mountains",
	cold_taiga: "§3Snowy Taiga",
	cold_taiga_hills: "§sSnowy Taiga Hills",
	cold_taiga_mutated: "§sSnowy Taiga Mountains",
	mega_taiga: "§2Old Growth Pine Taiga",
	mega_taiga_hills: "§4Mega Taiga",
	redwood_taiga_mutated: "§2Old Growth Spruce Taiga",
	redwood_taiga_hills_mutated: "§mRedwood Taiga",
	swampland: "§qSwamp",
	swampland_mutated: "§qSwamp Hills",
	mangrove_swamp: "§mMangrove Swamp",
	desert: "§6Desert",
	desert_hills: "§6Desert Hills",
	desert_mutated: "§gDesert Lakes",
	jungle: "§qJungle",
	jungle_hills: "§qJungle Hills",
	jungle_mutated: "§qModified Jungle",
	jungle_edge: "§2Sparse Jungle",
	jungle_edge_mutated: "§qJungle Edge",
	bamboo_jungle: "§2Bamboo Jungle",
	bamboo_jungle_hills: "§2Bamboo Jungle Hills",
	birch_forest: "§aBirch Forest",
	birch_forest_hills: "§aBirch Forest Hills",
	birch_forest_mutated: "§aOld Growth Birch Forest",
	birch_forest_hills_mutated: "§aTall Birch Hills",
	roofed_forest: "§qDark Forest",
	roofed_forest_mutated: "§qRoofed Forest",
	savanna: "§pSavanna",
	savanna_plateau: "§pSavanna Plateau",
	savanna_mutated: "§pWindswept Savanna",
	savanna_plateau_mutated: "§pShattered Savanna",
	mushroom_island: "§uMushroom Fields",
	mushroom_island_shore: "§uMushroom Field Shore",
	extreme_hills: "§7Windswept Hills",
	extreme_hills_mutated: "§7Gravelly Mountains",
	extreme_hills_plus_trees: "§jWindswept Forest",
	extreme_hills_plus_trees_mutated: "§jGravelly Forest",
	extreme_hills_edge: "§7Mountain Edge",
	ocean: "§9Ocean",
	warm_ocean: "§bWarm Ocean",
	lukewarm_ocean: "§sLukewarm Ocean",
	cold_ocean: "§3Cold Ocean",
	frozen_ocean: "§tFrozen Ocean",
	deep_ocean: "§1Deep Ocean",
	deep_warm_ocean: "§sDeep Warm Ocean",
	deep_lukewarm_ocean: "§tDeep Lukewarm Ocean",
	deep_cold_ocean: "§1Deep Cold Ocean",
	deep_frozen_ocean: "§tDeep Frozen Ocean",
	legacy_frozen_ocean: "§tLegacy Frozen Ocean",
	mesa: "§cBadlands",
	mesa_bryce: "§hEroded Badlands",
	mesa_plateau: "§nBadlands Plateau",
	mesa_plateau_stone: "§jWooded Badlands",
	mesa_plateau_mutated: "§cModified Badlands",
	mesa_plateau_stone_mutated: "§jModified Wooded Badlands",
	forest: "§2Forest",
	forest_hills: "§2Wooded Hills",
	flower_forest: "§dFlower Forest",
	river: "§9River",
	frozen_river: "§bFrozen River",
	beach: "§eBeach",
	cold_beach: "§fSnowy Beach",
	stone_beach: "§7Stony Shore",
	ice_plains: "§fSnowy Plains",
	ice_plains_spikes: "§bIce Spikes",
	meadow: "§qMeadow",
	grove: "§jGrove",
	cherry_grove: "§dCherry Grove",
	snowy_slopes: "§iSnowy Slopes",
	stony_peaks: "§8Stony Peaks",
	jagged_peaks: "§8Jagged Peaks",
	frozen_peaks: "§tFrozen Peaks",
	ice_mountains: "§fSnowy Mountains",
	lush_caves: "§dLush Caves",
	dripstone_caves: "§nDripstone Caves",
	deep_dark: "§sDeep Dark",
	pale_garden: "§vPale Garden",
	hell: "§cNether Wastes",
	crimson_forest: "§mCrimson Forest",
	warped_forest: "§3Warped Forest",
	soulsand_valley: "§bSoul Sand Valley",
	basalt_deltas: "§8Basalt Deltas",
	the_end: "§5The End",
}
export const overworld_structures = [
    {
		id: 'igloo', x: -347.5, y: 71.06, z: -715.5,
		structure: 'Igloo', require: 'taiga',
		biome: biome_names.frozen_river,
		place: {x: -356, y: 69, z: -724},
	},
    {
		id: 'jungle_temple', x: -458.5, y: 70, z: 883.5,
		structure: 'Jungle Temple', require: 'jungle',
		biome: biome_names.jungle_edge,
		place: {x: -464, y: 65, z: 880},
	},
    {
        id: 'desert_pyramid', x: -761.5, y: 65, z: -270.5,
        structures: ['Desert Pyramid', 'Desert Well'], require: 'desert',
        biomes: [biome_names.desert_hills, biome_names.desert_lakes],
    },
    {
		id: 'ocean_monument', x: 675, y: 40, z: 376,  ///tp 680 ~ 376  //seed: 3612322357111126416  //old seed: -1672001255
		structure: 'Ocean Monument', require: 'mushroom_island',
		biome: biome_names.lukewarm_ocean,
		place: {x: 650, y: 34, z: 346},
	},
    {
		id: 'swamp_hut', x: -252.5, y: 67, z: 516.5,  
		structure: 'Swamp Hut', require: 'swamp',
		biome: biome_names.swamp_hills,
		place: {x: -257 , y: 64, z: 511},
	},
    {
		id: 'mineshaft', x: 696.5, y: 33, z: -232.5,
		structure: 'Mineshaft', require: 'badlands',
		biome: biome_names.modified_badlands,
		place: {x: 684, y: 31, z: -248},
	},
    {
		id: 'pillager_outpost', x: -901.5, y: 94, z: 379.5,  
		structure: 'Pillager Outpost', require: 'savanna',
		biome: biome_names.savanna_plateau,
		place: {x: -910, y: 80, z: 370},
	},
    {
		id: 'woodland_mansion', x: 531.5, y: 64.06, z: -860.5,
		structure: 'Woodland Mansion', require: 'dark_forest',
		biome: biome_names.roofed_forest,
		place: {x: 521, y: 63, z: -871},
	},
    {
		id: 'ancient_city', x: 157.5, y: -37, z: 764.5,
		structure: 'Ancient City', require: 'deep_dark',
		biome: biome_names.deep_dark,
		place: [{x: 134, y: -51, z: 749}, {x: 112, y: -51, z: 757}, {x: 153, y: -51, z: 720}, {x: 180, y: -51, z: 752}, {x: 151, y: -51, z: 775}],
	},
    {
        id: 'ocean_ruins', x: -640.5, y: 46, z: 262.5, icon: 'shipwreck',
        structures: ['Warm Ocean Ruins', 'Cold Ocean Ruins', 'Shipwreck'], require: 'ocean',
        biomes: [biome_names.deep_warm_ocean, biome_names.deep_cold_ocean, biome_names.deep_lukewarm_ocean]
	},
    {
		id: 'trail_ruins', x: 130.5, y: 53, z: -830.5,
		structure: 'Trail Ruins', require: 'birch',
		biome: biome_names.old_growth_pine_taiga,
		place: {x: 120, y: 39, z: -859},
	},
    {
		id: 'trial_chambers', x: 375.5, y: 9, z: -491.5,
		structure: 'Trial Chambers', require: 'cherry',
		biome: biome_names.old_growth_spruce_taiga,
		place: {x: 361, y: 7, z: -519},
	},
]
export const nether_structures = [
    {
		id: 'nether_fortress', x: 75.5, y: 53, z: 142.5,
		structure: 'Nether Fortress',
		place: {x: 64, y: 52, z: 112},
	},
    { 
		id: 'bastion_remnants', x: -97.5, y: 65, z: 92.5,
		structure: 'Bastion Remnants',
		place: {x: -109, y: 64, z: 79},
	},
    {
		id: 'ruined_portal', x: -283.5, y: 18, z: 142.5,
		structure: 'Ruined Portal',
		place: {x: -291, y: 9, z: 133},
	},
]
export const destinations = {
	starter_island: { coords: {x: 0.5, y: 64, z: 0.5}, place: {x: -7, y: 60, z: -7}},
	desert_island: { coords: {x: 0.5, y: 64, z: 96.5}, place: {x: -7 , y: 60, z: 89}},
	jungle_island: { coords: {x: -94.5, y: 64, z: 0.5}, place: {x: -103 , y: 60, z: -7}},
	taiga_island: { coords: {x: 0.5, y: 64.12, z: -95.5}, place: {x: -7, y: 60, z: -103}},
	swamp_island: { coords: {x: 95.5, y: 64, z: 1.5}, place: {x: 89, y: 60, z: -7}},
	savanna_island: { coords: {x: 95.5, y: 64, z: 96.5}, place: {x: 89, y: 60, z: 89}},
	mushroom_island: { coords: {x: -94.5, y: 64, z: 95.5}, place: {x: -103, y: 60, z: 89}},
	birch_island: { coords: {x: -94.5, y: 64, z: -94.5}, place: {x: -103, y: 60, z: -103}},
	roofed_island: { coords: {x: 95.5, y: 64, z: -94.5}, place: {x: 89, y: 60, z: -103}},
	badlands_island: { coords: {x: 0.5, y: 64, z: 191.5}, place: {x: -7, y: 60, z: 185}},
	cherry_island: { coords: {x: -190.5, y: 64, z: 0.5}, place: {x: -199, y: 60, z: -7}},
	pale_island: { coords: {x: -0.5, y: 64, z: -190.5}, place: {x: -7, y: 60, z: -199}},
	ocean_island: { coords: {x: 192.5, y: 64, z: 0.5}, place: {x:188, y: 58, z: -4}},
	amethyst_island: { coords: {x: -43.5, y: 32, z: 144.5}, place: {x: -53, y: 26, z: 139}},
	lush_island: { coords: {x: -143.5, y: 32, z: -47.5}, place: {x: -153, y: 26, z: -57}},
	dripstone_island: { coords: {x: 44.5, y: 32, z: -143.5}, place: {x: 38, y: 26, z: -152}},
	deep_dark_island: { coords: {x: 144.5, y: -32, z: 48.5}, place: {x: 138 , y:-36, z: 42}},
	nether_portal: { coords: {x: 1.5, y: 64, z: 0.5}, dimension: "nether", place: {x: -7, y: 60, z: -7}},
	crimson_island: { coords: {x: 95.5, y: 64, z: 0.5}, dimension: "nether", place: {x: 89, y: 60, z: -7}},
	warped_island: { coords: {x: -94.5, y: 64, z: 0.5}, dimension: "nether", place: {x: -103, y: 60, z: -7}},
	basalt_island: { coords: {x: 0.5, y: 64, z: 94.5}, dimension: "nether", place: {x: -7, y: 60, z: 89}},
	soulsand_island: { coords: {x: 0.5, y: 64, z: -95.5}, dimension: "nether", place: {x: -7, y: 60, z: -103}},
	the_end: { coords: {x: 100.5, y: 50, z: 0.5}, dimension: "the_end"},
}
;[...overworld_structures, ...nether_structures].forEach(({id, x, y, z, place}) => destinations[id] = {coords: {x, y, z}, place})
nether_structures.forEach(({id}) => destinations[id].dimension = 'nether')

export const restorable_structures = {
    warm_ocean_ruins: {
        place: { x: -656, y: 40, z: 240 },
        visit: "ocean_ruins"
    },
    cold_ocean_ruins: {
        place: { x: -640, y: 40, z: 272 },
        visit: "ocean_ruins"
    },
    shipwreck: {
        place: { x: -656, y: 40, z: 256 },
        visit: "ocean_ruins"
    },
    desert_pyramid: {
        place: { x: -768, y: 62, z: -272 },
        visit: "desert_pyramid"
    },
    desert_well: {
        place: { x: -775, y: 62, z: -281 },
        visit: "desert_pyramid"
    },
}
Object.keys(destinations).forEach(id => {
	if (destinations[id].place) restorable_structures[id] = {
		place: destinations[id].place,
		visit: id
	}
})
