import "./startup.js"

import "./blocks/blocks.js"
import "./blocks/end_stone.js"
import "./blocks/redstone_ore.js"
import "./blocks/suspicious_blocks.js"
import "./blocks/coral.js"
import "./blocks/monster_spawners.js"

import "./items/eye_of_ender.js"
import "./items/totem.js"
import "./items/raw_ores.js"
import "./items/guidebook.js"
import "./items/scraped_trial.js"
import "./items/debug_stick.js"

import "./world/archeology.js"
import "./world/ore_mining.js"
import "./world/actionbar.js"
import "./world/stats.js"
import "./world/limited_vision.js"
import "./world/end_phantoms.js"
import "./world/the_end.js"
import "./world/slime_finder.js"
import "./world/cat_gifts.js"

import "./blocks/enderman_pickup.js"
import "./blocks/dragon_eggs.js"
import "./blocks/player_heads.js"
import "./blocks/sculk_shrieker.js"

import "./shutdown.js"